version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: donation_system
    container_name: donation_system
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    networks:
      - donation_system

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - donation_system

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rfA4@X5cXPw*eqCduTE
      MYSQL_DATABASE: donation_system
      MYSQL_USER: root
      MYSQL_PASSWORD: rfA4@X5cXPw*eqCduT
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - donation_system

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rfA4@X5cXPw*eqCduTE
    ports:
      - "8080:80"
    networks:
      - donation_system

networks:
  donation_system:

volumes:
  dbdata:
